### ISSUE TITLE
Documentation for arquillian-payara-server-remote connector appears to be out of date

### ISSUE THREAD

**Issue by phillipross** [payara/Payara-Community-Documentation#12]
The docs for this connector are still out of date in the new repo.  This issue was previously filed in the now-archived repo:  [Payara-Server-Documentation issue #709](https://github.com/payara/Payara-Server-Documentation/issues/709)

The documentation payara-remote arquillian container has documentation for `<artifactId>arquillian-payara-server-4-remote</artifactId>` instead of `<artifactId>arquillian-payara-server-remote</artifactId>`

I've been attempting to get arquillian to deploy and test against a remote payara server running in a separate docker container but bumped into problems, and I'm not sure if I'm using the proper configuration for the connector or not.

I've filed an issue against the connector here:
[payara/ecosystem-arquillian-connectors#51](https://github.com/payara/ecosystem-arquillian-connectors/issues/51)

**Comment by OndroMih** [comment]
This is fixed by https://github.com/payara/Payara-Community-Documentation/commit/0164dd7a6f2bd5c3b7212d8d5004a95ac7debb8f#diff-747177805d0c8252cdd419d580978208.
