### ISSUE TITLE
Incorrect example of deploying multiple applications from a Maven repository

### ISSUE THREAD

**Issue by avpinchuk** [payara/Payara-Community-Documentation#125]
https://docs.payara.fish/community/docs/5.2020.7/documentation/payara-micro/deploying/deploy-program-maven.html#deploying-multiple-applications-from-a-maven-repository

Last code snippet does not work as expected. Only application from the second `addDeploymentFromGAV` call will be deployed because they both have same context (same as `atrifactId`).

**Comment by OndroMih** [comment]
This is a limitation of Payara Micro API, which derives the context from the artifact name. This is just an example, the artifact `fish.payara.testing:clusterjsp` doesn't even exist in any public repository, or does it? I'll just change the second line to some other artifact name.

**Comment by OndroMih** [comment]
I've changed the example: https://github.com/payara/Payara-Community-Documentation/commit/6f8a27f61280e0b7f284559b356add46fefb7d63

**Comment by avpinchuk** [comment]
> This is a limitation of Payara Micro API, which derives the context from the artifact name. This is just an example, the artifact `fish.payara.testing:clusterjsp` doesn't even exist in any public repository, or does it? I'll just change the second line to some other artifact name.

No, does not exists. But some peoples may be confused and will try to deploy same artifact with different versions.
