### ISSUE TITLE
HSTS Enabled Documentation Incorrect

### ISSUE THREAD

**Issue by mzaum** [payara/Payara-Community-Documentation#159]
The [HSTS Enabled ](https://docs.payara.fish/community/docs/5.2021.3/documentation/payara-server/server-configuration/http/protocols/ssl-options.html#configuration-hsts-enabled) documentation is incorrect (or I guess Payara's implementation of HSTS could be incorrect, I haven't verified).

The documentation states:

> When enabled, the server will respond to insecure requests with the Strict-Transport-Security header. While these requests often return a 301 directing the client to the secure site, this header instructs the requester to make all connections to this site secure for the next year.

However, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security):

> The Strict-Transport-Security header is ignored by the browser when your site is accessed using HTTP; this is because an attacker may intercept HTTP connections and inject the header or remove it. When your site is accessed over HTTPS with no certificate errors, the browser knows your site is HTTPS capable and will honor the Strict-Transport-Security header.

Sending HSTS over insecure requests, per above, is pointless.  HSTS should only go out over secure requests.  So either the documentation is wrong, or the implementation is.

**Comment by OndroMih** [comment]
I had a look at [the code](https://github.com/payara/Payara/pull/5179/files) and it looks like HSTS can be enabled for both HTTP and HTTPS. There's no check whether the listener uses SSL or not. There's only a check whether the SSL configuration exists and HSTS is enabled in it but that can be present even if SSL itself is disabled.

Therefore the docs are wrong. When HSTS is enabled, the HSTS header is added both to insecure and secure responses. Browser should ignore the HSTS header in insecure responses so it only makes sense to enable HSTS in Payara Server for secure HTTP listeners.
